import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { contrastRatio } from './contrast';
// The real config, not a copy of its values re-typed here. Fix round 1's
// review finding: this file used to re-declare BRAND/BRAND_DARK/etc. as its
// own local constants, so every assertion below checked those constants
// against each other and NEVER read `tailwind.config.js` at all -- setting
// `brand: '#FFFFFF'` in the config left this whole file green. Importing
// the config directly (it's a plain ESM module -- `package.json`'s
// `"type": "module"` makes this a real import, not a build step) means a
// wrong value in the one place Tailwind itself reads is the one place that
// makes these assertions fail. See this file's own mutation proof, recorded
// in the Task 2/3 report, for what that failure looks like.
import tailwindConfig from '../../tailwind.config.js';

const colors = tailwindConfig.theme.extend.colors;
const BRAND = colors.brand;
const BRAND_DARK = colors['brand-dark'];
const ACCENT = colors.accent;
const ACCENT_DARK = colors['accent-dark'];
const INK = colors.ink;
const CREAM = colors.cream;
const CREAM_ALT = colors['cream-alt'];
const WASH = colors.wash;
const WASH_WARM = colors['wash-warm'];
const WHITE = '#FFFFFF';

// Every hex the old palette used, lowercased for comparison. `6b8b59` is the
// green itself; `5a7349` is its hover partner. Both appeared as bare literals
// inside className strings -- and, it turned out, inside a plain CSS file
// and the root HTML shell too, neither of which the original version of
// this guard could see (fix round 1: it only walked `.ts`/`.tsx` under
// `src/`, so `src/index.css`'s scrollbar/focus-ring colours and
// `index.html`'s no-JS fallback link colour all still shipped the green
// after the sweep "passed").
const RETIRED = ['6b8b59', '5a7349'];

// Files this guard deliberately does not read, and why each one is safe to
// skip rather than a gap matching the one above:
//
//   - `src/test/palette.test.ts`: this file. The RETIRED array above would
//     otherwise flag itself.
//   - `scripts/favicons.mjs`: still hardcodes `SAGE = '#6B8B59'`. The
//     favicon lockup is generated by rendering real markup in a browser
//     (see that file's own header) and is explicitly out of scope for this
//     phase -- the spec defers the favicon rework out of Phase 1 by
//     decision -- so its green is a known, parked TODO, not something this
//     sweep missed. Named explicitly rather than covered by a directory
//     exclusion so that anything else added under `scripts/` later is still
//     checked.
const IGNORED = ['src/test/palette.test.ts', 'scripts/favicons.mjs'];

// `src/` (components, admin, content, tests) and `scripts/` (build-time
// Node scripts -- Tailwind never reads these, but a literal here is still
// the same stale colour a future reader could copy from) are walked in
// full; extensions cover every place a colour literal has actually turned
// up so far: `.ts`/`.tsx` for component and script source, `.css` for the
// global stylesheet.
// The token's own distance from white, in the same units
// e2e/section-washes.spec.ts measures the rendered band in. This is the
// arithmetic claim; the pixel claim lives in e2e/ and neither substitutes
// for the other -- src/index.css paints a fixed overlay this function cannot
// see, and only the browser knows whether the section paints above it.
function meanPointsBelowWhite(hex: string): number {
  const n = parseInt(hex.replace('#', ''), 16);
  return 255 - (((n >> 16) & 255) + ((n >> 8) & 255) + (n & 255)) / 3;
}

function sourceFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) return sourceFiles(full);
    return /\.(ts|tsx|css|mjs)$/.test(full) ? [full] : [];
  });
}

describe('the retired green', () => {
  it('appears nowhere in src/, scripts/, or index.html, including comments and CSS', () => {
    // Comments count. Tailwind's scanner is a plain text extractor with no
    // JS parser, so a hex inside a comment is indistinguishable from one in
    // a className as far as the generated CSS is concerned, and a stale hex
    // in a comment is a lie to the next reader either way.
    //
    // `index.html` is checked explicitly, by name, rather than folded into
    // a directory walk: it lives at the repo root, outside both `src/` and
    // `scripts/`, and it is the one HTML file Tailwind's own content glob
    // actually scans (`tailwind.config.js`'s `content` array), so a literal
    // there is exactly as live a hazard as one inside `src/`.
    const offenders = [...sourceFiles('src'), ...sourceFiles('scripts'), 'index.html']
      .filter((file) => !IGNORED.includes(file))
      .filter((file) => {
        const text = readFileSync(file, 'utf8').toLowerCase();
        return RETIRED.some((hex) => text.includes(hex));
      });
    expect(offenders).toEqual([]);
  });
});

describe('the brand palette meets WCAG AA where it carries meaning', () => {
  it('puts readable text on a brand-blue surface', () => {
    // #C8D8E8 is a light surface at 1.45:1 against white. Ink on it is the
    // only readable pairing, and this is the assertion that stops a future
    // edit from putting white text on a blue button.
    expect(contrastRatio(BRAND, INK)).toBeGreaterThanOrEqual(4.5);
    expect(contrastRatio(BRAND, WHITE)).toBeLessThan(4.5);
  });

  it('lets the accent carry text on white and white text on itself', () => {
    expect(contrastRatio(ACCENT, WHITE)).toBeGreaterThanOrEqual(4.5);
  });

  it('keeps accent-dark readable on white too, for the hover state', () => {
    // Fix round 1: `hover:text-brand-dark` on a light background measured
    // 2.13:1 -- the same failure as brand-as-text, just one shade darker.
    // accent-dark is the hover partner for every accent-as-text site now,
    // so it needs the same AA floor accent itself is held to above.
    expect(contrastRatio(ACCENT_DARK, WHITE)).toBeGreaterThanOrEqual(4.5);
  });

  it('keeps the hover shade distinguishable from the base', () => {
    // The eye needs to see the hover happen. Equal colours would pass every
    // other assertion in this file.
    expect(contrastRatio(BRAND, BRAND_DARK)).toBeGreaterThan(1.1);
    expect(contrastRatio(ACCENT, ACCENT_DARK)).toBeGreaterThan(1.1);
  });

  it('keeps ink readable on both creams', () => {
    expect(contrastRatio(CREAM, INK)).toBeGreaterThanOrEqual(4.5);
    expect(contrastRatio(CREAM_ALT, INK)).toBeGreaterThanOrEqual(4.5);
  });

  it('keeps the focus ring visible against a white surface', () => {
    // Reads the actual outline colour out of src/index.css's
    // `button:focus-visible, a:focus-visible` rule, not a copy of its value
    // re-typed here -- otherwise this assertion can never fail on its
    // stated subject: swap that rule back to brand (1.45:1 on white, well
    // under the 3:1 this is checking for) and ACCENT here would still be
    // ACCENT, still >= 4.5 by the assertion two tests up, and this test
    // would stay green while the real page's focus ring failed 1.4.11.
    const css = readFileSync('src/index.css', 'utf8');
    const match = css.match(
      /button:focus-visible,\s*a:focus-visible\s*\{\s*outline:\s*2px solid (#[0-9A-Fa-f]{6});/
    );
    if (!match) throw new Error('focus-visible outline rule not found in src/index.css');
    const focusRingColor = match[1];

    // This is a non-text UI indicator (WCAG 1.4.11), which needs 3:1 rather
    // than body text's 4.5:1.
    expect(contrastRatio(focusRingColor, WHITE)).toBeGreaterThanOrEqual(3);
  });
});

// Computed with this repo's own src/test/contrast.ts, and recorded so the next
// reader can see how much margin each assertion below is standing on rather
// than only that it passes:
//
//   #E6EDF5  ink 13.48   accent 5.11   white 1.180   mean drop 17.67
//   #F5EEE4  ink 13.81   accent 5.23   white 1.152   mean drop 18.00
//
// Both carry a shallowest channel 10 below white, which is what
// e2e/section-washes.spec.ts's own floor holds the rendered band to.
describe('the section washes are washes, and readable', () => {
  it.each([['wash', WASH], ['wash-warm', WASH_WARM]])(
    '%s sits 15 to 20 points below white, which is where a band reads as a band', (_n, hex) => {
      expect(meanPointsBelowWhite(hex)).toBeGreaterThanOrEqual(15);
      expect(meanPointsBelowWhite(hex)).toBeLessThanOrEqual(20);
    });
  it.each([['wash', WASH], ['wash-warm', WASH_WARM]])('%s carries ink at AA', (_n, hex) => {
    expect(contrastRatio(hex, INK)).toBeGreaterThanOrEqual(4.5);
  });
  it.each([['wash', WASH], ['wash-warm', WASH_WARM]])(
    '%s carries the accent at AA, because that is the only foreground colour this palette allows on a light surface',
    (_n, hex) => { expect(contrastRatio(hex, ACCENT)).toBeGreaterThanOrEqual(4.5); });
  it.each([['wash', WASH], ['wash-warm', WASH_WARM]])(
    '%s is a surface, not a colour: white text on it is still unreadable and always will be',
    (_n, hex) => { expect(contrastRatio(hex, WHITE)).toBeLessThan(1.5); });
  it('the two washes are distinguishable from white and from each other', () => {
    // Equal-to-white would pass the AA assertions above and defeat the whole
    // task; equal-to-each-other would pass them too and remove the boundary
    // between the last two bands on the homepage.
    expect(contrastRatio(WASH, WHITE)).toBeGreaterThan(1.1);
    expect(contrastRatio(WASH_WARM, WHITE)).toBeGreaterThan(1.1);
    expect(WASH).not.toBe(WASH_WARM);
  });
});
