// Real HTML5 drag-and-drop, driven through page.mouse rather than
// locator.dragTo(). Lifted out of e2e/block-editor.spec.ts, whole, rather
// than copied a second time into e2e/editor-surface.spec.ts: Section B (this
// same plan) deletes block-editor.spec.ts, so this is the only place this
// gesture can live once that happens, and editor-surface.spec.ts needs it
// today for a dish row and a homepage section, neither of which is a block.
//
// WHY THIS IS NOT locator.dragTo(), recorded here because the first version
// of block-editor.spec.ts was, and the failure looked exactly like a broken
// handle.
//
// dragTo presses on the source and releases on the target. Chromium starts a
// native drag only when the mouse MOVES with the button held while the
// pointer is still on the element it pressed, and dragTo's own two-move
// workaround does not reliably cross that threshold once Playwright has to
// scroll between the press and the move -- instrumented directly (every
// mouse and drag event logged at window in the capture phase, see
// block-editor.spec.ts's own git history for the full trace), dragTo
// produced no dragstart at all against an off-screen target, while the
// sequence below produced a correct dragstart/dragover/drop/dragend every
// time. So the handle was never broken and the product needed no change --
// what the sequence below adds is the one thing dragTo skips: a small move
// while the pointer is still on the handle, which is what crosses
// Chromium's own drag threshold. Everything after that is the browser's
// real HTML5 drag, generated by Chromium from real pointer input rather
// than dispatched as synthetic DragEvents, which is the whole reason this
// lives in e2e/ rather than a jsdom test.
import { expect, type Locator, type Page } from '@playwright/test';

// Nothing type-checks this directory (tsconfig.json references app, node and
// worker only), so a `!` on boundingBox would fail as "Cannot read
// properties of null" fifty lines from anything that names a handle. Read
// once, checked once, and the message says which handle and what was wrong
// with it.
async function boxOf(handle: Locator, what: string): Promise<{ x: number; y: number; width: number; height: number }> {
  const box = await handle.boundingBox();
  if (box === null) throw new Error(`${what} has no box: the handle is not being rendered, or it is not on screen`);
  return box;
}

// Press on a drag handle and cross Chromium's drag threshold, but do not
// release. Split from dropOnto so a caller can assert on the mid-flight
// state (e.g. the dragged row's own dimming), which is the only moment that
// state is observable at all.
//
// `settled`, if given, is an extra condition to wait for before polling the
// handle for stillness. block-editor.spec.ts's own reason for waiting on a
// NAMED condition first, rather than trusting the stability poll alone: a
// debounced validation pass landing shortly after a freshly-added block
// shifts the whole panel's layout, and the poll below -- two animation
// frames -- can land entirely inside the quiet moment just BEFORE that
// shift, report "stable", and let a press start that the shift then slides
// out from under. Neither of editor-surface.spec.ts's own two callers add
// anything before dragging (no fresh row, no debounce to race), so both
// call this with no `settled` locator.
export async function startDragging(page: Page, handle: Locator, settled?: Locator): Promise<void> {
  if (settled !== undefined) {
    await expect(settled, 'the condition the caller said to wait for never appeared').toBeVisible();
  }

  await handle.scrollIntoViewIfNeeded();
  await expect
    .poll(
      async () =>
        handle.evaluate(
          (el) =>
            new Promise<boolean>((resolve) => {
              const before = el.getBoundingClientRect();
              requestAnimationFrame(() =>
                requestAnimationFrame(() => {
                  const after = el.getBoundingClientRect();
                  resolve(before.x === after.x && before.y === after.y);
                }),
              );
            }),
        ),
      { message: 'the handle never stopped moving, so a drag pressed on it could not have started' },
    )
    .toBe(true);

  const box = await boxOf(handle, 'the handle the drag starts on');
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  // Still on the handle. This is the move dragTo never makes.
  await page.mouse.move(box.x + box.width / 2 + 6, box.y + box.height / 2 + 6, { steps: 3 });

  // Defence in depth, and a named failure instead of a silent one. If the
  // page moves anyway, this says so here rather than fifty lines later as an
  // array that did not change.
  const stillOnTheHandle = await handle.evaluate(
    (el, point: { x: number; y: number }) => {
      const under = document.elementFromPoint(point.x, point.y);
      return under !== null && (under === el || el.contains(under));
    },
    { x: box.x + box.width / 2 + 6, y: box.y + box.height / 2 + 6 },
  );
  expect(
    stillOnTheHandle,
    'the page moved under the pointer between the press and the nudge, so no drag started',
  ).toBe(true);
}

// Complete a drag started by startDragging: move onto the target (scrolling
// it into view first is safe now, mid-drag -- the browser follows the
// pointer rather than losing the gesture), fire a second move over it
// (`dragover` is what the drop depends on, and one move is one dragover),
// then release.
export async function dropOnto(page: Page, handle: Locator): Promise<void> {
  await handle.scrollIntoViewIfNeeded();
  const box = await boxOf(handle, 'the handle the drag is dropped onto');
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2, { steps: 10 });
  await page.mouse.move(box.x + box.width / 2 + 1, box.y + box.height / 2 + 1, { steps: 5 });
  await page.mouse.up();
}
