import { describe, it, expect } from 'vitest';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  stays,
  emptyReport,
  rewriteJson,
  rewriteJsonText,
  rewriteSource,
  plan,
  CODE_FILES,
} from '../rewrite-image-refs.mjs';
// The census tool, imported rather than re-implemented here. These two
// collectors are what produced docs/image-inventory.json, by walking the tree
// from a different script with its own tests, so counting with them and
// comparing against plan()'s report is two implementations disagreeing when
// one of them is wrong -- not a number this file wrote being read back.
import { collectFromCode, collectFromJson } from '../image-inventory.mjs';
import { IMAGE_BASE } from '../../src/shared/image-host';
// A rewritten file read back in the spelling it had before the migration.
//
// This is what lets every expectation over the real tree below hold in BOTH
// states, before a human has run this script and after. That is a
// requirement rather than a nicety: docs/cloudflare-cutover.md §21 has a
// human run the rewrite and commit its output, and a test file describing
// only the tree it was written against is red in exactly that commit.
// Measured before this existed, by feeding one pass's output back into
// plan(): five named tests here failed, both of the ones watching the
// stylesheet among them.
import { siteRootForm } from '../../src/test/siteRootForm';

const CONTENT_DIR = join('src', 'content');
const CONTENT_FILES = readdirSync(CONTENT_DIR).filter((name) => name.endsWith('.json'));
const ALL_FILES = [...CONTENT_FILES.map((name) => join(CONTENT_DIR, name)), ...CODE_FILES];
// A stand-in for image-manifest.json that marks EVERY key verified. The real
// manifest does not exist yet -- Task 4's migration cannot run until the R2
// custom domain is connected -- and a hand-written partial one would only test
// the refusal, never the rewrite.
const everythingVerified = {
  objects: new Proxy({}, {
    get: (_t, key) => (typeof key === 'string' ? { verifiedAt: '2026-09-01T00:00:00.000Z' } : undefined),
    has: () => true,
  }),
};

const nothingVerified = { objects: {} };

function read(file) {
  return readFileSync(file, 'utf-8');
}

// The tree as it stood BEFORE the migration, whichever state it is really in:
// a file whose references have already moved is handed back in its old
// spelling, a file whose references have not is handed back untouched. The
// refusal has nothing to refuse once every reference has moved, so the one
// test that must see a photograph on this origin reads through this instead
// of off the disk.
function readPreMigration(file) {
  return siteRootForm(readFileSync(file, 'utf-8'));
}

// The list of code files is the one input this test cannot restate without
// making itself vacuous. Dropping src/index.css from the module's list left
// every assertion in this file green, because the file supplied its own copy.
// Pinned against the census instead, which was generated by a different script
// walking the tree.
describe('the code files it rewrites', () => {
  const fromInventory = [...new Set(
    JSON.parse(readFileSync(join('docs', 'image-inventory.json'), 'utf-8'))
      .references.map((reference) => reference.file)
      .filter((file) => file.startsWith('src/') && !file.endsWith('.json')),
  )].sort();

  it('is exactly the set of non-JSON files the inventory found references in', () => {
    expect([...CODE_FILES].sort()).toEqual(fromInventory);
  });

  it('includes the stylesheet that paints the whole-page texture', () => {
    expect(CODE_FILES).toContain('src/index.css');
  });
});

describe('the prefix this script writes', () => {
  // Two copies of one string. This is the only thing that stops them drifting:
  // the script is plain node and cannot import the TypeScript module.
  it('is the same prefix src/shared/image-host.ts defines', () => {
    const report = emptyReport();
    rewriteJson({ image: '/food/x.webp' }, everythingVerified, report);
    expect(report.mapping.get('/food/x.webp')).toBe(`${IMAGE_BASE}/food/x.webp`);
  });

  it('percent-encodes a filename with a space, the way imageUrl does', () => {
    const report = emptyReport();
    rewriteJson({ image: '/food/boozy donna.webp' }, everythingVerified, report);
    expect(report.mapping.get('/food/boozy donna.webp')).toBe(`${IMAGE_BASE}/food/boozy%20donna.webp`);
  });
});

describe('what deliberately does not move', () => {
  it('keeps the share card at the site root', () => {
    expect(stays('/og-image.jpg')).toBe(true);
  });

  it('keeps both menu pdfs, which Task 19 moves with their upload path', () => {
    expect(stays('/menus/food-menu.pdf')).toBe(true);
    expect(stays('/menus/drinks-menu.pdf')).toBe(true);
  });

  it('keeps the favicons and the icons index.html names', () => {
    expect(stays('/favicon-32.png')).toBe(true);
    expect(stays('/apple-touch-icon.png')).toBe(true);
    expect(stays('/icon-192.png')).toBe(true);
  });

  it('keeps a reference that has already been moved, which is what makes a re-run safe', () => {
    expect(stays(`${IMAGE_BASE}/food/pizza1.webp`)).toBe(true);
  });

  it('moves an ordinary photograph', () => {
    expect(stays('/food/pizza1.webp')).toBe(false);
  });

  it('reports a kept path as skipped rather than silently passing over it', () => {
    const report = emptyReport();
    rewriteJson({ a: '/og-image.jpg', b: '/menus/food-menu.pdf' }, everythingVerified, report);
    expect(report.skipped).toEqual(['/og-image.jpg', '/menus/food-menu.pdf']);
    expect(report.changed).toEqual([]);
  });
});

describe('the refusal', () => {
  it('records a reference whose object is not in the manifest at all', () => {
    const report = emptyReport();
    rewriteJson({ image: '/food/x.webp' }, nothingVerified, report);
    expect(report.missing).toEqual(['/food/x.webp']);
    expect(report.changed).toEqual([]);
  });

  it('records a reference whose object is in the manifest but unverified', () => {
    const report = emptyReport();
    const manifest = { objects: { 'food/x.webp': { kind: 'derivative', reason: 'read-back HTTP 404' } } };
    rewriteJson({ image: '/food/x.webp' }, manifest, report);
    expect(report.missing).toEqual(['/food/x.webp']);
  });

  it('leaves an unverified reference exactly as it was', () => {
    expect(rewriteJson({ image: '/food/x.webp' }, nothingVerified, emptyReport()))
      .toEqual({ image: '/food/x.webp' });
  });

  // The whole safety argument. The CLI computes every file's new contents
  // BEFORE it looks at report.missing, so a single unverified object stops all
  // twelve files rather than nine of them.
  it('plans every file without writing any of them', () => {
    const report = emptyReport();
    const pending = plan(readPreMigration, nothingVerified, report, { contentFiles: CONTENT_FILES, codeFiles: CODE_FILES });
    expect(report.missing.length).toBeGreaterThan(0);
    expect(pending).toEqual([]);
  });

  it('refuses a plan() call that was never given the content half', () => {
    expect(() => plan(read, everythingVerified, emptyReport(), { codeFiles: [] })).toThrow();
  });
});

// Against the real tree, not a fixture. A fixture could only prove the regex
// matches strings this file wrote.
describe('the real content and code files', () => {
  const report = emptyReport();
  const pending = plan(read, everythingVerified, report, { contentFiles: CONTENT_FILES, codeFiles: CODE_FILES });
  const written = new Map(pending.map(({ file, after }) => [file, after]));

  // What a file holds once the rewrite has been applied to it: plan()'s text
  // where it moved something, the file's own text where it did not. Before a
  // human runs the script that is thirteen new texts; after, it is the tree
  // exactly as committed. Every question below is asked of THIS rather than of
  // `written`, which is what makes the answers the same on both sides of that
  // commit.
  const rewritten = (file) => written.get(file) ?? read(file);

  // Every reference in one file, counted by the inventory's own collectors.
  function census(file, text) {
    const found = [];
    if (file.endsWith('.json')) collectFromJson(JSON.parse(text), file, found);
    else collectFromCode(text, file, found);
    return found.map((entry) => entry.path);
  }

  // Read off docs/image-inventory.json rather than typed here, and that
  // artefact was produced by walking the tree from a different script. Four of
  // its eighty-five references are the D1 rows Task 7 rewrites through the
  // publish endpoint, which this script never touches.
  const inventory = JSON.parse(readFileSync(join('docs', 'image-inventory.json'), 'utf-8'))
    .references.filter((reference) => !reference.file.startsWith('d1:'));
  const inventoryFiles = [...new Set(inventory.map((reference) => reference.file))].sort();

  // Counted over the pre-migration spelling, so the number means the same
  // thing whether or not the rewrite has run.
  const references = ALL_FILES.flatMap((file) => census(file, siteRootForm(rewritten(file))));
  // Counted over the tree as it is on disk right now: what is left to move.
  const stillOnThisOrigin = ALL_FILES
    .flatMap((file) => census(file, read(file)))
    .filter((path) => !stays(path));

  it('accounts for every committed reference the inventory counted', () => {
    expect(references).toHaveLength(inventory.length);
  });

  it('moves seventy-seven of them and leaves four where they are', () => {
    expect(references.filter((path) => !stays(path))).toHaveLength(77);
    expect(references.filter(stays)).toHaveLength(4);
  });

  // plan()'s own report against the census, which two different scripts
  // produced. Before the rewrite has run both sides are the same seventy-seven
  // paths; after it, both are empty.
  it('rewrites every reference still on this origin, and nothing else', () => {
    expect([...report.changed].sort()).toEqual([...stillOnThisOrigin].sort());
  });

  it('leaves exactly three distinct references alone', () => {
    expect([...new Set(report.skipped)].sort()).toEqual([
      '/menus/drinks-menu.pdf',
      '/menus/food-menu.pdf',
      '/og-image.jpg',
    ]);
  });

  it('finds nothing unverified when every object is verified', () => {
    expect(report.missing).toEqual([]);
  });

  // The file list, which is the one thing this test cannot restate without
  // making itself vacuous -- dropping src/index.css from the module's list
  // once left all thirty-seven assertions here green. Both halves are pinned:
  // the files that hold a reference at all, against the inventory, and the
  // files this run actually wrote, against what is left to move.
  it('reads every file the inventory found a reference in', () => {
    const holding = ALL_FILES.filter((file) => census(file, siteRootForm(rewritten(file))).length > 0);
    expect(holding.sort()).toEqual(inventoryFiles);
  });

  it('writes exactly the files that still hold a reference on this origin', () => {
    const owed = ALL_FILES.filter((file) => census(file, read(file)).some((path) => !stays(path)));
    expect([...written.keys()].sort()).toEqual(owed.sort());
  });

  // The reason the JSON is edited as text. JSON.stringify(value, null, 2)
  // reformats four of these files -- menus.json alone grows by 28 bytes -- and
  // that whitespace would land in the same commit as a seventy-seven-reference
  // rewrite and in the bytes the D1 floor is later compared against.
  //
  // The file on disk is the independent side of this comparison. Rewriting
  // `before` and then undoing only the URL substitutions has to give `before`
  // back exactly; a writer that reflowed the JSON would survive the undo and
  // fail here.
  it.each(CONTENT_FILES)('%s changes only its reference strings, never its formatting', (name) => {
    const file = join(CONTENT_DIR, name);
    const before = siteRootForm(rewritten(file));
    const after = rewriteJsonText(before, everythingVerified, emptyReport());
    expect(siteRootForm(after)).toBe(before);
  });

  it('leaves the four hand-formatted files hand-formatted', () => {
    // Named, because these are the four JSON.stringify would have reflowed.
    for (const name of ['dishes.json', 'menus.json', 'pages.json', 'site.json']) {
      const after = rewritten(join(CONTENT_DIR, name));
      expect(after, name).not.toBe(JSON.stringify(JSON.parse(after), null, 2) + '\n');
    }
  });

  it('rewrites the whole-page texture in the stylesheet, not just the tsx', () => {
    expect(rewritten('src/index.css')).toContain(`url("${IMAGE_BASE}/hero/brick.webp")`);
    expect(rewritten('src/index.css')).not.toContain('url("/hero/brick.webp")');
  });

  it('leaves the mocktail pdf download link on this origin', () => {
    expect(rewritten('src/components/SignatureMocktails.tsx')).toContain('"/menus/food-menu.pdf"');
  });

  // THE MISS DETECTOR. Asked of every file this script reads rather than only
  // of the ones it wrote, because a file it failed to write is exactly the
  // case worth catching, and after the rewrite has run it writes none of them.
  it('leaves no photograph on this origin in any file it reads', () => {
    const CATEGORY = /["'`(](\/(?:food|hero|atmosphere|our_story|mocktails|press|experiences|team)\/[^"'`()\n]+)["'`)]/;
    for (const file of ALL_FILES) {
      const after = rewritten(file);
      expect(CATEGORY.test(after), `${file} still names ${CATEGORY.exec(after)?.[1]}`).toBe(false);
    }
  });
});

describe('rewriting a source file', () => {
  it('handles a css url(), a jsx attribute and a doc comment with one expression', () => {
    const report = emptyReport();
    const out = rewriteSource(
      'a { background-image: url("/hero/brick.webp"); }\n<img src="/food/x.webp" />\n// e.g. `/team/y.webp`\n',
      everythingVerified,
      report,
    );
    expect(out).toContain(`url("${IMAGE_BASE}/hero/brick.webp")`);
    expect(out).toContain(`src="${IMAGE_BASE}/food/x.webp"`);
    expect(out).toContain(`\`${IMAGE_BASE}/team/y.webp\``);
    expect(report.changed).toHaveLength(3);
  });

  // The `(` and `)` delimiters, which no file in this repository currently
  // needs -- src/index.css quotes its url() argument, so the quote branch
  // catches it. Written anyway, because removing the paren branch is a change
  // nothing else here can see, and an unquoted url() is valid CSS somebody
  // will write one day.
  it('rewrites an unquoted css url() too', () => {
    const out = rewriteSource('a { background-image: url(/hero/brick.webp); }', everythingVerified, emptyReport());
    expect(out).toBe(`a { background-image: url(${IMAGE_BASE}/hero/brick.webp); }`);
  });

  // The destination is a path now rather than a whole https URL, so an
  // already-rewritten reference is no longer invisible to this script's own
  // pattern -- `stays()` is what makes it a no-op instead, and this is run
  // against the everything-verified manifest precisely so nothing but
  // `stays()` can be what stops it.
  it('leaves an already-rewritten reference alone, so a second run is a no-op', () => {
    const once = rewriteSource('<img src="/food/x.webp" />', everythingVerified, emptyReport());
    expect(once).toContain(`${IMAGE_BASE}/food/x.webp`);
    expect(rewriteSource(once, everythingVerified, emptyReport())).toBe(once);
  });

  it('does not double the prefix on a reference that already carries it', () => {
    const report = emptyReport();
    const out = rewriteJson({ image: `${IMAGE_BASE}/food/x.webp` }, everythingVerified, report);
    expect(out).toEqual({ image: `${IMAGE_BASE}/food/x.webp` });
    expect(report.skipped).toContain(`${IMAGE_BASE}/food/x.webp`);
    expect(report.changed).toEqual([]);
  });
});

describe('rewriting json as text', () => {
  it('replaces a whole string token, never a path inside a longer one', () => {
    const text = '{\n  "a": "/food/x.webp",\n  "b": "/food/xx.webp"\n}\n';
    const out = rewriteJsonText(text, everythingVerified, emptyReport());
    expect(JSON.parse(out)).toEqual({ a: `${IMAGE_BASE}/food/x.webp`, b: `${IMAGE_BASE}/food/xx.webp` });
  });

  it('keeps compact hand formatting that JSON.stringify would reflow', () => {
    const text = '[\n  { "id": "food", "src": "/food/x.webp" }\n]\n';
    const out = rewriteJsonText(text, everythingVerified, emptyReport());
    expect(out).toBe(`[\n  { "id": "food", "src": "${IMAGE_BASE}/food/x.webp" }\n]\n`);
  });

  it('refuses a file where the text edit and the structural walk disagree', () => {
    // A path used as a KEY. The structural walk leaves keys alone; a blind
    // text replacement would not, and the mismatch is what catches it.
    const text = '{ "/food/x.webp": "/food/x.webp" }';
    expect(() => rewriteJsonText(text, everythingVerified, emptyReport())).toThrow(/structural/);
  });
});
